In [5]:
import numpy as np

In [6]:
players = np.array([
    "Virat",
    "Rohit",
    "Gill",
    "Rahul",
    "Pant"
])

runs = np.array([78, 45, 102, 67, 89])

balls = np.array([56, 39, 90, 58, 61])

In [17]:
index_of_highest = np.argmax(runs)
print("Highest Scorer")
print(f"{players[index_of_highest]} : {runs[index_of_highest]}")


Highest Scorer
Gill : 102


In [18]:
index_of_lowest = np.argmin(runs)
print("Lowest Scorer")
print(f"{players[index_of_lowest]} : {runs[index_of_lowest]}")

Lowest Scorer
Rohit : 45


In [23]:
strike_rate = np.array((runs / balls) * 100)

print("Strike Rate of all players:\n")



for player, strike_rate in zip(players, strike_rate):
    print(f"{player}: {strike_rate:.2f}")

Strike Rate of all players:

Virat: 139.29
Rohit: 115.38
Gill: 113.33
Rahul: 115.52
Pant: 145.90


In [26]:
average_runs = np.array(runs/len(runs))
print(average_runs)

[15.6  9.  20.4 13.4 17.8]


In [28]:
average_runs = np.mean(runs)
print(average_runs)

76.2


In [33]:
players_above_average = np.where(runs>average_runs)[0]
print("Players with above average score")
for index in players_above_average:
    print(f"{players[index]}: {runs[index]}")

Players with above average score
Virat: 78
Gill: 102
Pant: 89


In [36]:
sort_by_runs = np.sort(runs)[::-1]
print(sort_by_runs)

[102  89  78  67  45]


In [ ]:
best_strike_rate = np.max(strike_rate)
print(best_strike_rate)

In [ ]:
fifties_And_Centuries =np.where((runs>=50) & (runs<=100))[0].size
print(fifties_And_Centuries)

[0 3 4]
