In [2]:
from PIL import Image
import numpy as np

In [17]:
img = Image.open("img1.png").convert("L")
print(img)
# print(img.shape)
print(img.size)
print(img.height)
print(img.width)

<PIL.Image.Image image mode=L size=1685x933 at 0x19BF49D6650>
(1685, 933)
933
1685


In [13]:
image_array = np.array(img)
print(image_array)

[[43 43 43 ... 44 44 44]
 [43 43 44 ... 43 44 43]
 [43 43 44 ... 44 43 43]
 ...
 [43 43 42 ... 35 36 36]
 [42 41 42 ... 36 36 36]
 [44 41 41 ... 37 37 39]]


In [20]:
print(image_array.shape)
print(image_array.shape[0])
print(image_array.shape[1])
print(image_array.dtype)

(933, 1685)
933
1685
uint8


In [ ]:
bright_image = image_array + 50
dark_image = np.clip(image_array -50,0,255) # 0 and 255 are the min and max range

Image.fromarray(bright_image).save("bright_image.png") #save
Image.fromarray(dark_image).show() #show

In [ ]:
increase_contrast = np.clip(128+1.1*(image_array-128),0,255)
Image.fromarray(increase_contrast).show()

decrease_contrast = np.clip(128+0.9*(image_array-128),0,255)
Image.fromarray(decrease_contrast).show()

In [40]:
image_inversion = np.clip(255-image_array, 0, 255)
Image.fromarray(image_inversion).show()

In [ ]:
horizontal_flip = np.flip(image_array, axis=1)
horizontal_flip = image_array[:, ::-1] # with slicing 
# Image.fromarray(horizontal_flip).show()

In [ ]:
vertical_flip = np.flip(image_array, axis=0)
# Image.fromarray(vertical_flip).show()

In [ ]:
shape = image_array.shape
cropped_image = image_array[0:shape[0]//2, 0:shape[1]]
# Image.fromarray(cropped_image).show()
print(shape)

(933, 1685)


In [56]:
shape = image_array.shape
cropped_Image =  image_array[0:shape[0],shape[1]//4:3*shape[1]//4]
Image.fromarray(cropped_Image).show()

In [64]:
ninty_rot= np.rot90(image_array)

oneeighty_rot= np.rot90(ninty_rot)

twoseventy_rot= np.rot90(oneeighty_rot)

Image.fromarray(ninety_rot).show()

Image.fromarray(oneeighty_rot).show()

Image.fromarray(twoseventy_rot).show()





In [ ]:
max_pixel=np.max(image_array)

min_pixel=np.min(image_array)

average_brightness= np.mean(image_array)

print(max_pixel,min_pixel,int(average_brightness))

255 0 65.78553086466871


In [80]:
# convert the image into pure black and white image using thresholding
threshold = 128

image_bw = np.where(image_array >threshold, 255, 0).astype("uint8")

print(image_bw.dtype)

Image.fromarray(image_bw).show()


uint8


In [83]:
arr= np.zeros(256).astype("int64")
flat = image_array.flatten()
for val in flat:
    arr[val]+=1

print(arr)    

[ 5634 10387  8436  5953  6227  6566  5804  6117  5764  5016  4909  5117
  5252  6013  6692  6772  6960  9554  7313  5465  4672  4608  5136  4601
  4699  5135  4931  5236  4959  4300  4597  4335  4173  6336  7523  7011
  6728  6024  5858  7490  8262  8652 10686 11581 13339 16675 19032 18176
 18112 18623 19040 20523 22160 24627 25977 26240 27880 30170 28029 26036
 24773 27346 29051 27916 26884 26889 26377 24352 24584 25387 23290 22616
 23048 23682 23324 22407 20570 19497 20375 19567 18101 17408 17907 18654
 18504 18652 17317 15864 14915 14287 14391 13753 13276 12435 12323 11763
 11157 10870 10141  9603  9651  9042  8519  7626  7402  6685  6392  6089
  5714  5293  5073  5009  4737  4571  4573  4988  5295  4695  4370  3782
  3004  2554  2125  2055  2349  2309  1696  1347   976   890   829   728
   707   729   712   703   757   762   762   651   587   606   578   588
   620   629   572   585   545   602   573   573   512   461   534   421
   415   367   342   347   308   296   304   282   