In [1]:
import numpy as np

In [41]:
A = np.arange(1,10).reshape(3,3)
B= np.arange(10,19).reshape(3,3)
B[2,2]=50
A[2,2]=100

In [42]:
print(A)
print(B)

[[  1   2   3]
 [  4   5   6]
 [  7   8 100]]
[[10 11 12]
 [13 14 15]
 [16 17 50]]


In [ ]:
result_Sum_Matrix = np.add(A,B)
print(result_Matrix)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [17]:
result_Differenece_Matrix = np.subtract(B,A)
print(result_Differenece_Matrix)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [18]:
result_Dot_Matrix = np.dot(B,A)
print(result_Dot_Matrix)

[[138 171 204]
 [174 216 258]
 [210 261 312]]


In [21]:
transpose_A = np.transpose(A)
print(transpose_A)
transpose_B= np.transpose(B)
print(transpose_B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[10 13 16]
 [11 14 17]
 [12 15 18]]


In [44]:
determenant_Of_A= np.linalg.det(A)
print(determenant_Of_A)
determinant_Of_B= np.linalg.det(B)
print(determinant_Of_B)


-273.0
-95.99999999999999


In [43]:
inverse_Of_A = np.linalg.inv(A)

inverse_Of_B = np.linalg.inv(B)

print(f"inverse of A is : {inverse_Of_A} and inverse of B is : {inverse_Of_B}")

inverse of A is : [[-1.65567766  0.64468864  0.01098901]
 [ 1.31135531 -0.28937729 -0.02197802]
 [ 0.01098901 -0.02197802  0.01098901]] and inverse of B is : [[-4.63541667  3.60416667  0.03125   ]
 [ 4.27083333 -3.20833333 -0.0625    ]
 [ 0.03125    -0.0625      0.03125   ]]


In [45]:
trace_Of_A= np.trace(A)
trace_Of_B= np.trace(B)
print(f"trace of A is : {trace_Of_A} and trace of B is : {trace_Of_B}")

trace of A is : 106 and trace of B is : 74


In [46]:
rank_Of_A= np.linalg.matrix_rank(A)
rank_Of_B= np.linalg.matrix_rank(B)
print(f"rank of A is : {rank_Of_A} and rank of B is : {rank_Of_B}")

rank of A is : 3 and rank of B is : 3


In [51]:
A_i= np.eye(A.shape[0])
res= np.array_equal(A, A_i)
res1 = np.array_equal(B,A_i)
print(res,res1)

False False


In [52]:
arr1 = np.array([1,2,3])
arr2= np.array([1,2,3])

res= np.array_equal(arr1,arr2)
print(res)

True


In [62]:
print((A==np.eye(A.shape[0])).all())
print((B==np.eye(B.shape[0])).all())

False
False


In [66]:
res = np.allclose(A, np.eye(A.shape[0]))
print(res)
res1 = np.allclose(B, np.eye(B.shape[0]))
print(res1)

False
False


In [70]:
isSymmetric_A= (A == np.transpose(A)).all()
print(isSymmetric_A)
isSymmetric_B= (B == np.transpose(B)).all()
print(isSymmetric_B)

False
False
