In [3]:
import numpy as np

In [7]:
marks_arr= np.array([78, 56, 89, 45, 92, 67, 38, 81, 59, 73])
marks_arr

array([78, 56, 89, 45, 92, 67, 38, 81, 59, 73])

In [8]:
names = np.array([
    "Yash",
    "Aman",
    "Riya",
    "Priya",
    "Rahul",
    "Neha",
    "Karan",
    "Anjali",
    "Mohit",
    "Sneha"
])

In [100]:
highest_Marks = np.max(marks_arr)
index=np.argmax(marks_arr)
name_of_topper=names[index]
print(name_of_topper)
int(highest_Marks)

Rahul


92

In [101]:
lowest_Marks = np.min(marks_arr)
index=np.argmin(marks_arr)
name_of_lowest=names[index]
print(name_of_lowest)
int(lowest_Marks)

Karan


38

In [9]:
average_Marks = np.mean(marks_arr)
int(average_Marks)

67

In [10]:
median_Marks = np.median(marks_arr)
int(median_Marks)

70

In [ ]:
students_above_40=marks_arr[marks_arr>40].size
index_Of_Passed = np.where(marks_arr > 40)[0]
for index in index_Of_Passed:
    print(names[index], marks_arr[index])


Yash 78
Aman 56
Riya 89
Priya 45
Rahul 92
Neha 67
Anjali 81
Mohit 59
Sneha 73


In [109]:
students_below_40=marks_arr[marks_arr<40].size
index_Of_Failed = np.where(marks_arr < 40)[0]
for index in index_Of_Failed:
    print(f"{names[index]}:{marks_arr[index]}")

Karan:38


In [89]:
topper = np.argmax(marks_arr)
topper

np.int64(4)

In [90]:
students_scored_above_average=np.where(marks_arr>average_Marks)[0]
students_scored_above_average

array([0, 2, 4, 7, 9])

In [91]:
asc_marks_arr = np.sort(marks_arr)
asc_marks_arr

array([38, 45, 56, 59, 67, 73, 78, 81, 89, 92])

In [92]:
dsc_marks_arr = np.sort(marks_arr)[::-1]
dsc_marks_arr

array([92, 89, 81, 78, 73, 67, 59, 56, 45, 38])

In [94]:
total_students = marks_arr.size
total_students

10