In [1]:
import numpy as np

In [97]:

cities = np.array(["Delhi", "Mumbai", "Bangalore"])

temperature = np.array([
    [36, 37, 38, 35, 34, 36, 37],  # Delhi
    [30, 31, 32, 31, 30, 29, 30],  # Mumbai
    [25, 24, 26, 27, 25, 24, 26]   # Bangalore
])

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

In [7]:
for city, temp in zip(cities, temperature):
    print(f"Temperatures for {city} : {temp}")

Temperatures for Delhi : [36 37 38 35 34 36 37]
Temperatures for Mumbai : [30 31 32 31 30 29 30]
Temperatures for Bangalore : [25 24 26 27 25 24 26]


In [18]:
average_temp= np.array([])
for i in range(len(temperature)):
    average_temp  = np.append(average_temp,np.mean(temperature[i]))
    
for city,average in zip(cities, average_temp):
    print(f"Average temperature for {city} : {average}")

Average temperature for Delhi : 36.142857142857146
Average temperature for Mumbai : 30.428571428571427
Average temperature for Bangalore : 25.285714285714285


In [21]:
average_temp_day_wise = np.mean(temperature, axis=0)

for day, average in zip(days, average_temp_day_wise):
    print(f"Average temperature for {day} : {average:.2f}")

Average temperature for Mon : 30.33
Average temperature for Tue : 30.67
Average temperature for Wed : 32.00
Average temperature for Thu : 31.00
Average temperature for Fri : 29.67
Average temperature for Sat : 29.67
Average temperature for Sun : 31.00


In [ ]:
overall_avg_temp=np.mean(temperature)

print(f"Overall average temperature for the week : {overall_avg_temp:.2f}")

Overall average temperature for the week : 30.62


In [95]:
r,c= np.where(temperature==np.max(temperature))
print(r,c)
print(temperature.shape)
print(f"The maximum temperature is of : {cities[r][0]} {temperature[r,c][0]}" )

[0] [2]
(3, 7)
The maximum temperature is of : Delhi 38


In [75]:
matrix= np.arange(1,10).reshape(3,3)
print(matrix)

matrix[2][2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.int64(9)

In [98]:
r,c= np.where(temperature == np.min(temperature))
print(r,c)
print(f"The coldest day is in {cities[r][0]} : {temperature[r,c][0]}")

[2 2] [1 5]
The coldest day is in Bangalore : 24


In [ ]:
highest_Temperature_Of_Each_City = np.max(temperature,axis=1)
for city,highest_Temperature in zip(cities,highest_Temperature_Of_Each_City):

      print(f"Highest temperature of {city} : {highest_Temperature}")

[38 32 27]
Highest temperature of Delhi : 38
Highest temperature of Mumbai : 32
Highest temperature of Bangalore : 27


In [101]:
lowest_Temperature_Of_Each_City = np.min(temperature,axis=1)

for city,lowest_Temperature in zip(cities,lowest_Temperature_Of_Each_City ):

      print(f"Lowest temperature of {city} : {lowest_Temperature }")

Lowest temperature of Delhi : 34
Lowest temperature of Mumbai : 29
Lowest temperature of Bangalore : 24


In [114]:
hottest_Day_Of_Each_City = np.argmax(temperature,axis=1)
print(hottest_Day_Of_Each_City)

for city,day in zip(cities,hottest_Day_Of_Each_City):
      print(f"Hottest day of {city} : {days[day]}")

[2 2 3]
Hottest day of Delhi : Wed
Hottest day of Mumbai : Wed
Hottest day of Bangalore : Thu


In [115]:
coldest_Day_Of_Each_City = np.argmin(temperature,axis=1)

for city,day in zip(cities,coldest_Day_Of_Each_City):
      print(f"Coldest day of {city} : {days[day]}")

Coldest day of Delhi : Fri
Coldest day of Mumbai : Sat
Coldest day of Bangalore : Tue


In [118]:
highest_Temperature = np.max(temperature)
coldest_Temperature = np.min(temperature)

print(f"The highest temperature of the week is : {highest_Temperature}")
print(f"The coldest temperature of the week is : {coldest_Temperature}")

The highest temperature of the week is : 38
The coldest temperature of the week is : 24


In [ ]:
average_Temperature_Above_30 = np.mean(temperature,axis=1)


for city, avg_Temp in zip(cities,average_Temperature_Above_30):

      if(avg_Temp>30):

               print(f"{city} city has above temperature than 30")

Delhi city has above temperature than 30
Mumbai city has above temperature than 30


In [125]:
avg= np.mean(temperature,axis=1)
sortes_indices = np.argsort(avg)

for index in sortes_indices:
    print(cities[index], avg[index])

Bangalore 25.285714285714285
Mumbai 30.428571428571427
Delhi 36.142857142857146


In [126]:
sum_Of_Each_Column = np.sum(temperature,axis=0)
print(sum_Of_Each_Column)


[91 92 96 93 89 89 93]
